### ISSUE TITLE
Handle bad credentials, show message to user

### ISSUE THREAD

**Issue by ckelner** [ckelner/js-aws-reservations-comparison#13]
see:
<img width="818" alt="screen shot 2016-01-17 at 10 43 26 am" src="https://cloud.githubusercontent.com/assets/133862/12378294/398a64e0-bd07-11e5-8b94-5b6fb2d44ac2.png">

**Comment by ryansydnor** [comment]
:+1: - ran into this and took me a bit to track it down.

**Comment by ckelner** [comment]
@ryansydnor my apologies!  I'll try to get that sorted in short order.  Thanks for reporting it.
