### ISSUE TITLE
[Feature] - Support IAM Instance Profile Credentials

### ISSUE THREAD

**Issue by ryansydnor** [ckelner/js-aws-reservations-comparison#22]
IAM Instance profile credentials use three pieces of auth: access key, secret key, AND token. It would be nice to be able to optionally include a token to authenticate.

**Comment by ryansydnor** [comment]
@ckelner - I'll have a PR for your review shortly.

**Comment by ckelner** [comment]
@ryansydnor awesome :+1:

**Comment by ryansydnor** [comment]
Check it out! https://github.com/ckelner/AWSResco/pull/39
